<a href="https://colab.research.google.com/github/Aira10/Basic1/blob/master/5_Functions_to_Generate_Tensors_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1YYonnc_Czk7yGJXHM6ypcB8GtNXj0oU9')

     |████████████████████████████████| 71kB 3.1MB/s 



## **5 Functions to Generate Tensors using Pytorch**

Pytorch is essentially an open source machine learning framework developed by Facebook's AI research group. Pytorch uses dynamic computation unlike other deep learning frameworks (e.g. TensorFlow), making it flexible and easier to develop complex models. The use of classes, structures and loops make it easier to understand and use, compared to frameworks that use a different programming style. 

This notebook has compiled 5 tensor functions that can be used to create tensors. The first two functions are based on simple ideas of creating and arranging a tensor, whereas the following three functions generate mathematical equivalent forms of tensors- complex, heavyside step and polar.

- function 1: empty
- function 2: arrange
- function 3: complex
- function 4: heavyside step
- function 5: polar

Prerequisite: install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - Empty function

Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument 'size'. 'Size' takes in the rows and columns of the expected tensor.

In [ ]:
# Example 1 : Creating an uninitialized tensor with 3 rows and 2 columns
input = torch.empty(3,2)
torch.zeros_like(input)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Size takes in '3' as the number of rows and '2' as the number of columns. 

In [ ]:
# Example 2 - Creating a tensor 3D tensor 
input = torch.empty(4,3,2)
torch.zeros_like(input)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

Size generates a tensor with 4 splits of 3X2 size each

In [ ]:
input = torch.empty()
torch.zeros_like(input)

TypeError: ignored

Empty requires atleast one parameter as its size value. The size of the new tensor is undetermined if empty does not contain any arguments.

A easy function to implement when an uninitialized tensor of any size is needed.

Saving

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/01-tensor-operations


'https://jovian.ai/airavati97/01-tensor-operations'

## Function 2 - Arrange Function

Returns a 1-D tensor of size [(end-start)/step] with values from the interval [start, end) taken with common difference step beginning from start.
Parameters are-
start (Number) – the starting value for the set of points. Default: 0
end (Number) – the ending value for the set of points
step (Number) – the gap between each pair of adjacent points. Default: 1

In [ ]:
# Example 1 - working
torch.arange(1, 10, 0.5)


tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

Creating a tensor with values from 1 to 10 (not including 10) by incrementing in steps of 0.5

In [ ]:
# Example 2 - working
torch.arange(-25, -15, 0.75)

tensor([-25.0000, -24.2500, -23.5000, -22.7500, -22.0000, -21.2500, -20.5000,
        -19.7500, -19.0000, -18.2500, -17.5000, -16.7500, -16.0000, -15.2500])

Creating a tensor with values from -25 to -15 (not including -15) by incrementing in steps of 0.75

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(10,0,1)

RuntimeError: ignored

if the start value is greater than the stop value, the step should be -ve, and vice versa

Allows to generate a tensor with elements differing by a constant value

Saving

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/01-tensor-operations


'https://jovian.ai/airavati97/01-tensor-operations'

Mathematical Functions

## Function 3 - Complex Function

Constructs a complex tensor with its real part equal to real and its imaginary part equal to imag.

Parameters:
[1] real (Tensor) – The real part of the complex tensor. Must be float or double.
 [2] imag (Tensor) – The imaginary part of the complex tensor. Must be same dtype as real.



In [ ]:
# Example 1 - working

real = torch.tensor([2, 2.2], dtype=torch.float32)
imaginary = torch.tensor([3.5, 4.5], dtype=torch.float32)
z = torch.complex(real, imaginary)
z

tensor([2.0000+3.5000j, 2.2000+4.5000j])

Creating two tensor values- one with the real part as 2 and imaginary part as 3.5, and the other with the real part as 2.2 and imaginary part as 4.5; represented in real and imaginary coordinate form 

In [ ]:
# Example 2 - working
real = torch.tensor([-2], dtype=torch.float32)
imaginary = torch.tensor([3.5, 4.5,-6.7], dtype=torch.float32)
z = torch.complex(real, imaginary)
z

tensor([-2.+3.5000j, -2.+4.5000j, -2.-6.7000j])

Creating three tensor values- all with the real part as 2 and imaginary part as 3.5,4,5 and -6.7

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
real = torch.tensor([], dtype=torch.float32)
imaginary = torch.tensor([3.5, 4.5,-6.7], dtype=torch.float32)
z = torch.complex(real, imaginary)
z

RuntimeError: ignored

Generating a tensor with real part as empty is not possible, if no real part,enter 0

In [ ]:
#when no real part exists, enter 0
real = torch.tensor([0], dtype=torch.float32)
imaginary = torch.tensor([3.5, 4.5,-6.7], dtype=torch.float32)
z = torch.complex(real, imaginary)
z

tensor([0.+3.5000j, 0.+4.5000j, 0.-6.7000j])

In [ ]:
# Example 4 - breaking (to illustrate when it breaks)
real = torch.tensor([], 
imaginary = torch.tensor([3.5, 4.5,-6.7], dtype=torch.float32)
z = torch.complex(real, imaginary)
z

SyntaxError: ignored

not possible to perform computation when dtype not specified for one element

In [ ]:
# Example 5- breaking (to illustrate when it breaks)
real = torch.tensor([0])
imaginary = torch.tensor([3.5, 4.5,-6.7])
z = torch.complex(real, imaginary)
z

RuntimeError: ignored

not possible to perform computation when dtype not specified for both elements

Saving

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - Heavyside Step function

Computes the Heaviside step function for each element in input. The Heaviside step function is defined as:

heaviside(input,values)= {

0,if input < 0

values,if input == 0

1,if input > 0

​}	
Parameters

[1]input (Tensor) – the input tensor.

[2]values (Tensor) – The values to use where input is zero.

In [ ]:
# Example 1 - working
input = torch.tensor([-1.5, 0, 2.0])
values = torch.tensor([0.5])
torch.heaviside(input, values)


tensor([0.0000, 0.5000, 1.0000])

According to the input, the new tensor generated has values

0 as the first element -1.5 is less than 0

0.5 as the second element of input is 0 and is replaced by 'values' parameter

1 as the final element of input is greater than 1 

In [ ]:
# Example 2 - working
input = torch.tensor([-1.5, 0, 2.0,0])
values = torch.tensor([0.5,-9,0,10])
torch.heaviside(input, values)


tensor([ 0., -9.,  1., 10.])

According to the input, the new tensor generated has values

0 as the first element -1.5 is less than 0

-9 as the second element of input is 0 and is replaced by corresponding index in 'values' parameter

1 as the next element of input is greater than 1

10 as the final element of input is 0 and hence replaced by corresponding index in 'values' parameter

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
input = torch.tensor([-1.5, 0, 2.0,0,0,7])
values = torch.tensor([0.5,-9,-6,7])
torch.heaviside(input, values)

RuntimeError: ignored

The dimentions of the 'values' tensor are incorrect for the given input tensor

To be used if set values are needed to be inserted into locations with a null entry, but the remaining tensor should remain as either 0 or 1 to differentiate between entries greater and less than 0 (i.e. +ve and -ve values)

Saving

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/01-tensor-operations


'https://jovian.ai/airavati97/01-tensor-operations'



```
# This is formatted as code
```

## Function 5 - Polar Function

Constructs a complex tensor whose elements are Cartesian coordinates corresponding to the polar coordinates with absolute value abs and angle angle.

out=abs⋅cos(angle)+abs⋅sin(angle)⋅j

Parameters

[1]abs (Tensor) – The absolute value the complex tensor. Must be float or double.

[2]angle (Tensor) – The angle of the complex tensor. Must be same dtype as abs.

*the value of pi should be converted by multiplying with np (numpy is a python library)

In [ ]:
# Example 1 - working
import numpy as np
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi / 2, 5 * np.pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([6.1232e-17+1.j, 6.1232e-16+2.j], dtype=torch.complex128)

Two tensor values are generated

One with absolute value 1 and the angle as pi/2

Second with absolute value 2 and the angle as 5pi/2

where pi is in radians (after conversion)

In [ ]:
# Example 2 - working
import numpy as np
abs = torch.tensor([-0.7,-9,6,3.2], dtype=torch.float64)
angle = torch.tensor([4*np.pi / 2, 3*np.pi / 2,4*np.pi / 3,5 * np.pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([-7.0000e-01+1.7145e-16j,  1.6533e-15+9.0000e+00j,
        -3.0000e+00-5.1962e+00j,  9.7972e-16+3.2000e+00j],
       dtype=torch.complex128)

A series of elements having the abs part as a -ve numbers or a float, and different angles have been created by the polar function, by choosing abs value and corresponding angle value

In [ ]:
# Example 3 - working
import numpy as np
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([np.pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z

tensor([6.1232e-17+1.j, 1.2246e-16+2.j], dtype=torch.complex128)

Same angle is used for both abs part

In [ ]:
# Example 4 - break
import numpy as np
abs = torch.tensor([1, 2], dtype=torch.float64)
angle = torch.tensor([pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z

NameError: ignored

pi value has to be defined and * by np

In [ ]:
# Example 5 - empty abs (results in empty tensor)

import numpy as np
abs = torch.tensor([], dtype=torch.float64)
angle = torch.tensor([np.pi / 2], dtype=torch.float64)
z = torch.polar(abs, angle)
z


tensor([], dtype=torch.complex128)

Used when the polar form has to be generated from a set of abs and angle values

Saving

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion
 5 functions to create tensors have been described with examples in this notebook.In the next notebook, the traning of a model will be explored.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://towardsdatascience.com/introduction-to-py-torch-13189fb30cb3
*w3schools.com/python/

In [ ]:
jovian.commit(project='5 Functions to Generate Tensors using Pytorch')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/5-functions-to-generate-tensors-using-pytorch


'https://jovian.ai/airavati97/5-functions-to-generate-tensors-using-pytorch'

Saving work

In [68]:
jovian.commit(project='5 Functions to Generate Tensors using Pytorch')
jovian.commit(project='my-project')
jovian.submit(assignment="5 Functions to Generate Tensors using Pytorch")

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/5-functions-to-generate-tensors-using-pytorch
[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/airavati97/my-project
[jovian] Detected Colab notebook...


[jovian] Error: Please provide the project argument e.g. jovian.commit(project='my-project')


In [70]:
jovian.commit(assignment="5 Functions to Generate Tensors using Pytorch")


[jovian] Detected Colab notebook...


[jovian] Error: Please provide the project argument e.g. jovian.commit(project='my-project')
